theme="catppuccin_mocha"
# theme="gruvbox"

[editor.cursor-shape]
insert="bar"

[editor.whitespace.render]
newline = "all"
tab = "all"

nbsp = "none"
nnbsp = "none"
space = "none"

[keys.normal]
# use system clipboard
# p = "paste_clipboard_after"
# P = "paste_clipboard_before"
# y = "yank_to_clipboard"
# Y = "yank_joined_to_clipboard"
# R = "replace_selections_with_clipboard"
# d = ["yank_to_clipboard", "delete_selection_noyank"]

# Delete to the end of line
# D = ["select_mode", "goto_line_end", "yank_to_clipboard", "delete_selection"]
D = ["select_mode", "goto_line_end", "delete_selection"]

C-k = "scroll_up"
C-j = "scroll_down"
C-h="jump_view_left"
C-l="jump_view_right"
K="hover"
V=["select_mode", "extend_line_below"]
C-p = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- zsh ~/.config/helix/yazi-picker.sh open"
C-f = ":sh zellij run -c -d left -- zsh ~/.config/helix/open-from-clipboard.sh"

[keys.select]
# use system clipboard
# p = "paste_clipboard_after"
# P = "paste_clipboard_before"
# y = "yank_to_clipboard"
# Y = "yank_joined_to_clipboard"
# R = "replace_selections_with_clipboard"
# d = ["yank_to_clipboard", "delete_selection_noyank"]

[keys.normal.g]
h = "goto_first_nonwhitespace"
s = "goto_line_start"

[keys.insert]
j = {j = "normal_mode"}

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false
git-ignore = false
